[project]
name = "monorepo-py"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3-stubs~=1.42.1",
]

[tool.uv.workspace]
members = [
    "packages/sh_dendrite",
    "packages/sh_api",
    "packages/concurrency_test_harness",
]
