[project]
name = "concurrency-test-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sh-dendrite",
]

[tool.uv.sources]
sh-dendrite = { workspace = true }
