[project]
name = "sh_api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Howard Dierking", email = "howard@dierking.family" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "psycopg[binary]>=3.2.13",
    "pydantic>=2.12.5",
    "sh_dendrite",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
sh_dendrite = { workspace = true }